# Build spike create release

name: Build spike

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Set DATESTAMP
        run: |
          DATESTAMP="$(date --utc '+%Y.%m.%d')"
          echo "DATESTAMP=${DATESTAMP}" >> $GITHUB_ENV

      - name: Build GNU toolchain
        run: |
          root_directory=$(pwd)
          mkdir -p $root_directory/compress_files

          sudo apt-get install autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev
          git submodule update --depth 1 --init riscv-gnu-toolchain
          cd riscv-gnu-toolchain
          git submodule update --depth 1 --init --recursive newlib
          git submodule update --depth 1 --init --recursive binutils
          git clone --depth 1 https://github.com/gcc-mirror/gcc.git gcc-master
          toolchain_root_directory=$(pwd)
          ./configure --prefix=/opt/riscv --enable-multilib  --disable-gdb --with-cmodel=medany --with-gcc-src=$toolchain_root_directory/gcc-master
          sudo make
          sudo make build-sim SIM=qemu
          
          tar czvf riscv.tar.gz -C /opt/ riscv/
          mv riscv.tar.gz $root_directory/compress_files/

      # - name: Build spike
      #   run: |
      #     root_directory=$(pwd)

      #     sudo apt install device-tree-compiler
      #     git submodule update --init --recursive
      #     cd riscv-isa-sim/ci-tests
      #     sh build-spike
      #     build/install/bin/spike -h
          
      #     cp -R build/install/ spike/
      #     tar -czvf $root_directory/compress_files/ubuntu_x86_spike.tar.gz spike/

      # - name: Build pk
      #   run: |
      #     root_directory=$(pwd)
          
      #     wget https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2023.10.18/riscv64-elf-ubuntu-20.04-gcc-nightly-2023.10.18-nightly.tar.gz
      #     sudo mkdir /opt/riscv
      #     sudo tar -xzf riscv64-elf-ubuntu-20.04-gcc-nightly-2023.10.18-nightly.tar.gz -C /opt/
      #     export PATH=$PATH:/opt/riscv/bin
      #     git submodule update --init --recursive
      #     cd riscv-pk
      #     mkdir build
      #     cd build
      #     ../configure --prefix=/opt/riscv --host=riscv64-unknown-elf --with-arch=rv64imafdc_zifencei
      #     make install

      #     cp /opt/riscv/riscv64-unknown-elf/bin/pk pk
      #     tar -czvf $root_directory/compress_files/ubuntu_x86_pk.tar.gz pk
      
      - name: Creat release and Upload
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "weekly-${{ env.DATESTAMP }}"
          prerelease: true
          title: "RISCV weekly prebuild toolchain binary weekly-${{ env.DATESTAMP }}"
          files: |
            compress_files/*.tar.gz
